### ISSUE TITLE
Message limit - 14 MB

### ISSUE THREAD

**Issue by Fiodor94** [atech/postal#370] opened 2017-10-07 23:03 UTC
Hello there!

Thanks for this amazing project! I’m trying to find a way to raise the limit from 14 MB to about 40 – 50 MB per message. Is there a way to change the raw message type to a LONGBLOB, in order to “bypass” the 14 MB limit?

Thanks !

**Comment by catphish** [comment] 2017-10-09 08:24
I believe this is a duplicate of #268

**Closed by catphish** 2017-10-09 08:24 UTC
