### ISSUE TITLE
Feature Request: Token support on webhook / HTTP endpoint

### ISSUE THREAD

**Issue by zpnielsen** [atech/postal#475] opened 2018-01-24 20:31 UTC
Hi there,

I was hoping to see about adding a field or option to support passing a token in the webhook and HTTP endpoint for sending this data to platforms like Splunk (or whatever webapp), which require the token to be passed to validate the sending application.

The token (at least for Splunk) can be passed in the URL as ?token=xxxx-xxx-xxx, but that fails input validation via the Postal web interface.

Either way, would love to see this added.

Thanks!

**Comment by willpower232** [comment] 2018-01-25 09:38
The webhook from Postal will directly reference the message sent using information (hopefully) recorded by the app sending the message.

I'm not familiar with Splunk or similar platforms, are you able to record that information within it so that if the webhook was able to send to Splunk, it would know what message the webhook contents referred to?

**Comment by zpnielsen** [comment] 2018-01-30 17:38
This is for authentication. You can think of splunk like an ELK stack. It aggregates data and allows you to slice and dice it as needed.

In order to use a HTTP message receiver within splunk, you need to authenticate the messages using a token. That token can be passed in the header or as a query string. Currently, if I were to try to pass that token in a query string, the input form for the webhook does not permit the ?token=xxx-xxx-xxx to be inputted, as it fails with an invalid URL error.

**Comment by willpower232** [comment] 2018-01-31 21:43
My question was mainly how would Splunk know about the message you had sent in the first place but presumably you could add that data.

Can you send a screenshot of the error and URL you are trying to use? If Postal is upset about the query string, there might be others who get similarly affected.

**Comment by zpnielsen** [comment] 2018-02-01 14:48
In my use case, I'm not too worried about Splunk being aware of the message sent in the first place. I'm just using it to aggregate data regarding deliverability, bounces, etc.

See attached image regarding query string.

![image](https://user-images.githubusercontent.com/26369528/35684428-7467d09a-072c-11e8-9a40-0ee5b6f169d0.png)

**Comment by willpower232** [comment] 2018-02-03 11:21
Thanks for that, I've had a look at the code and believe I know what the problem is

If you have a look at the regex here https://github.com/atech/postal/blob/master/app/models/webhook.rb#L31

It allows `?` and `&` in URLs as if it will allow a querystring like yours however the `=` is missing.

Can you try adding `\=` just after the `\?` then restart Postal and see if that works?

**Comment by zpnielsen** [comment] 2018-02-04 09:23
Yep, that validates nicely now.

Thanks!

**Comment by willpower232** [comment] 2018-02-05 09:46
Jolly good, I've made a quick pull request to resolve this for everyone. Feel free to close the issue if you have no further related trouble.

**Comment by alexroosenstein** [comment] 2018-02-07 07:47
@zpnielsen does this work for you now?
I'm having issues with the query (the ?parameter=value part) being stripped from an HTTP endpoint, I'm guessing it's due to this line here
https://github.com/atech/postal/blob/master/lib/postal/http.rb#L18

which only uses the uri.path and not the query, but if it works for you it might be something else on my end.

**Closed** 2018-04-20 11:27 UTC
