### ISSUE TITLE
Unable to access HTTPS click track domain

### ISSUE THREAD

**Issue by willpower232** [atech/postal#97] opened 2017-05-04 12:28 UTC
As per https://github.com/atech/postal/issues/93, I have gained an SSL certificate for my click tracking domain.

I am unable to access any HTTPS click tracks, my browsers tell me that the connection was closed.

I believe the ports are forwarding correctly since I see "hello" when not using HTTPS.

Where else can I begin to debug this? I have restarted postal and updated it.

**Comment by adamcooke** [comment] 2017-05-04 12:37
Can you confirm the domain that you have configured so I can take a look?

**Comment by adamcooke** [comment] 2017-05-04 12:42
The fast server will cache SSL certificates (clearing the cache each day) which means you could end up with something invalid being cached. If you restart, you might find that it bursts into life for you.

**Comment by willpower232** [comment] 2017-05-04 12:58
I've managed to duplicate the issue with a new click tracking domain https://ct.postal.synergitech.net

I have restarted the server with no effect.

**Comment by elct9620** [comment] 2017-05-04 16:41
I have the same problem today.
After I tracking the problem, the problem is about the default SMTP cert.

https://github.com/atech/postal/blob/master/lib/postal/fast_server/client.rb#L144
When a new request sends to fast server, it cannot knows the request host.
So fast server use default SMTP cert, but after commit https://github.com/atech/postal/commit/caacaa7f9258f35a15056d1c9c82f4108c4876f8, we can skip SMTP cert setup.

So, the fast server cannot find default cert file and call `#servername_cb` to retrieve correct cert from the database.

I add some cert to `config/smtp.cert` and it works now, but I think it is not a good way to fix this.

**Comment by adamcooke** [comment] 2017-05-04 16:44
Thanks @elct9620. That does look like the issue. I'll be pushing a fix for that shortly.

**Comment by adamcooke** [comment] 2017-05-05 09:05
This is now fixed in the latest version. You'll need to run `postal initialize-config` again to generate new default certificates for the fast server (they don't need to be valid certs because the LE ones will take precedence). 

(Running `initialize-config` again will not touch any existing configuration)

**Closed by adamcooke** 2017-05-05 09:05 UTC
Labels: support

**Comment by willpower232** [comment] 2017-05-05 13:05
thanks adam, everything is working nicely now

**Comment by afanjul** [comment] 2017-05-09 16:44
Hi @adamcooke, I was in the same problem as people here, so I ran `postal initailize-config` to "update" certificates, now I see fast_server.cert and fast_server.key, however as its self signed I receive the typical warning screen from a browser. 

[Screenshot with my files](https://i.snag.gy/jrwJMS.jpg) 
[Screenshot with warning](https://i.snag.gy/Ec7Qbw.jpg)

Am I doing something wrong?

**Comment by afanjul** [comment] 2017-05-10 10:28
Sorry, I solved my issue, I was browsing to the "base" tracking domain (configured in postal.yml) instead of a "mail server" tracking domain (added by UI).
Thanks

**Comment by adamcooke** [comment] 2017-05-10 10:37
Glad you got it sorted.
