### ISSUE TITLE
IP POOL option not found in settings tab

### ISSUE THREAD

**Issue by johnLeads** [atech/postal#157] opened 2017-05-17 00:44 UTC
I want to assign multiple IPs to postal to Load Balance outgoing mails between them. How to do that???

**Comment by mattmartincouk** [comment] 2017-05-17 09:08
You won't have enabled it. See the config page in the wiki for details on the string to do that.

**Comment by catphish** [comment] 2017-05-17 09:12
This is probably a duplicate of #87 
Documentation will be added shortly.

**Closed by catphish** 2017-05-17 09:12 UTC
