### ISSUE TITLE
Possible bug when using parameters in traking urls

### ISSUE THREAD

**Issue by afanjul** [atech/postal#230] opened 2017-06-12 15:53 UTC
Hi there,
We have some issues when using urls with parameters in mails (and traking urls is active). 

I.e. when we use this url: `https://domain.com/rate/deskCases?dcID=51778&hash=12323&rate=Good`, the corresponding track url redirect to `https://domain.com/rate/deskCases?dcID=51778&amp;hash=12323&amp;rate=Good` that fails with 404 in our server end.

Looking at the database, efectively the url is malformed, due to html encoding so all of our urls (having query parameters) are wrong.

Maybe the problem is around [here](https://github.com/atech/postal/blob/1f64c61105be3f3c7ac9f79d90898d9e5e7970e1/lib/postal/message_parser.rb#L94)?

Could you please check it? thanks

**Comment by mattmartincouk** [comment] 2017-06-12 20:41
This is likely a duplicate of 115.

**Comment by catphish** [comment] 2017-06-13 15:33
Closing this ticket as a duplicate, but when this is fixed we will test against this case too.

**Closed by catphish** 2017-06-13 15:33 UTC
