### ISSUE TITLE
Status Pending

### ISSUE THREAD

**Issue by sahilsunesara** [atech/postal#214] opened 2017-06-06 06:47 UTC
Hello

I have sent some email's, but it shows pending only. Could you please tell me what will be the reason for this pending status

**Comment by TrollAH** [comment] 2017-06-07 09:38
I have the same problem. I restarted postal but the worker seems to be crashed somehow:

|| worker
|| Quantity            1
|| Command             bundle exec rake postal:worker
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.1         Stopping     25/05/2017   pid:5468     respawns:0      port:-        tag:-
|| => worker.2         Running      11:36        pid:22426    respawns:0      port:-        tag:-

**Comment by willpower232** [comment] 2017-06-07 09:51
@TrollAH have you considered restarting the entire server to clear the failed processes?

**Comment by sahilsunesara** [comment] 2017-06-13 14:14
Still, I have been waiting for the reply. Please reply me that why it shows pending status. Also, it's show's soft fail and then shows sent what will be the reason?

**Comment by stayallive** [comment] 2017-06-13 14:19
Pending means it has not been picked up by a worker yet. Make sure your worker is running.

A soft-fail can be expanded to view the details, reasons may vary but are usually because the IP you are sending from has never sent an email before causing recieving mail servers to be suspicous, the next try it will probably go through and be sent succesfully.

**Comment by sahilsunesara** [comment] 2017-06-13 14:22
Yes, my work is running but it's alway show pending

**Comment by willpower232** [comment] 2017-06-13 19:37
can you run `postal status` and show us everything it says?

**Comment by sahilsunesara** [comment] 2017-06-14 08:46
Procodile Version   1.0.16
Application Root    /opt/postal/app
Supervisor PID      1773
Started             2017-06-13 15:50:24 +0200

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      15:50        pid:1779     respawns:0      po                                                                                        rt:-        tag:-

|| worker
|| Quantity            1
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.5         Running      18:19        pid:4895     respawns:0      po                                                                                        rt:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.5           Running      18:19        pid:4908     respawns:0      po                                                                                        rt:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      18:19        pid:4899     respawns:0      po                                                                                        rt:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.5       Running      18:19        pid:4907     respawns:0      po                                                                                        rt:-        tag:-

**Comment by willpower232** [comment] 2017-06-14 09:22
did you remove the dates from the || =>lines or were they missing from your output? Mine looks like this:

```
|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      08/06/2017   pid:30654    respawns:0      port:-        tag:-
```

It might be worth giving yourself two workers to see what happens, add this to your `postal.yml` and then `postal restart`:

```
workers:
  quantity: 2
```

**Comment by sahilsunesara** [comment] 2017-06-14 09:25
how to make quantity: 2?

I didn't remove anything....I just installed with the help of quick install command like

**Comment by willpower232** [comment] 2017-06-14 09:42
You need to change `/opt/postal/config/postal.yml` and add the following lines:

```
workers:
  quantity: 2
```

**Comment by sahilsunesara** [comment] 2017-06-14 09:46
I have added into postal.yml and now show's 


* smtp.1 is not running (Unknown)

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      15:50        pid:1779     respawns:0      port:-        tag:-

**Comment by willpower232** [comment] 2017-06-14 10:40
can you send the whole postal status please

**Comment by sahilsunesara** [comment] 2017-06-14 10:43
Procodile Version   1.0.16
Application Root    /opt/postal/app
Supervisor PID      1738
Started             2017-06-14 12:33:18 +0200

 * smtp.1 is not running (Unknown)

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      12:42        pid:2268     respawns:1      port:-        tag:-

|| worker
|| Quantity            1
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.6         Running      12:42        pid:2249     respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.6           Running      12:42        pid:2261     respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Unknown      12:42        pid:2170     respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.6       Running      12:42        pid:2260     respawns:0      port:-        tag:-

**Comment by willpower232** [comment] 2017-06-14 10:52
can you try `postal stop` and then waiting a few minutes before using `postal start`?

**Comment by sahilsunesara** [comment] 2017-06-14 10:55
yes I tried to stop and start also tried restart VPS and start postal

I also would like to know from you that how many emails I can send using postal?
My VPS configuration is 2 vCores
2.4 GHz
8 GB RAM
40 GB SSD
Local RAID 10

**Comment by willpower232** [comment] 2017-06-14 11:59
You will have to examine the log files in `/opt/postal/log/` to find out why SMTP isn't working properly.

You should be able to send plenty of email, we have sent hundreds using half of that RAM.

**Comment by catphish** [comment] 2017-06-15 08:11
> did you remove the dates from the || =>lines or were they missing from your output? Mine looks like this:

I believe if it was started today, it will show the time rather than thee date.

**Comment by catphish** [comment] 2017-06-15 08:12
It's very strange that SMTP isn't running. Definitely check the logs, particularly smtp_server.log for clues as to why it's not starting.

**Comment by sahilsunesara** [comment] 2017-06-15 17:00
hello

i have reinstall my vps and again install postal using quick installation command but still i can see this postal status

root@vps422366:~# postal restart
Restarted web.1
Restarted worker.1 -> worker.2
Restarted cron.1 -> cron.2
Restarted smtp.1
Restarted requeuer.1 -> requeuer.2
root@vps422366:~# postal status
Procodile Version   1.0.16
Application Root    /opt/postal/app
Supervisor PID      24800
Started             2017-06-15 18:58:19 +0200

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      18:58        pid:24806    respawns:0      port:-        tag:-

|| worker
|| Quantity            1
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.2         Running      18:58        pid:24869    respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.2           Running      18:58        pid:24880    respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      18:58        pid:24873    respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.2       Running      18:58        pid:24881    respawns:0      port:-        tag:-



how to resolve this ?

**Comment by catphish** [comment] 2017-06-15 17:44
> how to resolve this ?

I'm afraid I don't understand what the problem is. It appears that all processes are marked as running:

```
|| => web.1 Running 18:58 pid:24806 respawns:0 port:- tag:-
|| => worker.2 Running 18:58 pid:24869 respawns:0 port:- tag:-
|| => cron.2 Running 18:58 pid:24880 respawns:0 port:- tag:-
|| => smtp.1 Running 18:58 pid:24873 respawns:0 port:- tag:-
|| => requeuer.2 Running 18:58 pid:24881 respawns:0 port:- tag:-
```

I something not working correctly?

**Comment by sahilsunesara** [comment] 2017-06-16 09:56
Hey look now

Is it correct now?

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      11:54        pid:7669     respawns:1      port:-        tag:-

|| worker
|| Quantity            2
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.3         Stopping     11:54        pid:7646     respawns:0      port:-        tag:-
|| => worker.4         Stopping     11:54        pid:7648     respawns:0      port:-        tag:-
|| => worker.5         Running      11:54        pid:7747     respawns:0      port:-        tag:-
|| => worker.6         Running      11:54        pid:7749     respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.3           Running      11:54        pid:7763     respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      11:55        pid:7753     respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.3       Running      11:54        pid:7762     respawns:0      port:-        tag:-

**Comment by catphish** [comment] 2017-06-16 10:59
Yes.

If something is not working, please open a new ticket, explain what is not working, and provide some logs demonstrating the problem.

**Closed by catphish** 2017-06-16 10:59 UTC

**Comment by applewood524** [comment] 2021-05-23 10:16
Hello
I have the same problem now. All messages are pending.
Please help me.

**Comment by willpower232** [comment] 2021-05-25 08:14
@applewood524 please don't comment on long-closed issues.

If you are still having problems, please open a new issue with the output of `postal status` to confirm everything is running.
