### ISSUE TITLE
Unknown keyword: endpoint

### ISSUE THREAD

**Issue by cmmata** [atech/postal#674] opened 2018-09-28 15:18 UTC
Hello,

3 days ago I started to receive an error in Postal's sentry instance: `ArgumentError: unknown keyword: endpoint` in `lib/postal/lets_encrypt.rb`. I attach a capture of Sentry error page to see the details. Looks like it doesn't find the `endpoint` variable, but I see it's defined in the same file. It was working normally since May more or less, when I installed Postal, and suddenly started to fail. By the way, I have no idea of Ruby, so maybe it's a novice fault.

I have ruby 2.3.7p456 (2018-03-28 revision 63024) and the latest postal (installed from this repository).
![screenshot_20180928_163737](https://user-images.githubusercontent.com/4223148/46217518-7bf96580-c342-11e8-9a34-6b8861523b7e.png)

**Comment by willpower232** [comment] 2018-10-02 09:10
Thanks for the report, I've not seen this one but I have seen random errors in sentry. The endpoint should be found within that same file so I'm not sure what its on about.

Are there multiple events for this issue or has it only occurred the once?

Does your click tracking work over SSL?

**Comment by cmmata** [comment] 2018-10-02 11:47
It has been happening every 30 minutes more or less since September 25th, so it has been 685 times at this time. And yes, it's working over SSL. If I open the domain with http or https, both return a 'Hello.' without error. It may be related with letsencrypt renewal, because it expires in 5 days.

**Comment by willpower232** [comment] 2018-10-02 16:14
Ah okay so it must have worked at least once. Can you verify that the file on your system exactly matches https://github.com/atech/postal/blob/master/lib/postal/lets_encrypt.rb?

If it does, can you try restarting your Postal and/or the whole server?

**Comment by cmmata** [comment] 2018-10-03 08:01
Yes, I think I checked some months ago that it renewed correctly the certificate, so it worked almost once. We have Postal installed by git on master branch, but anyway I checked that file manually and it's the same.

When I first see this issue (September 25th), the whole server had an uptime of 5 days because we restarted it on September 21. It was using ruby 2.4.1 and I restarted Postal server several times and then changed ruby version to 2.3.7 to see if it was a version problem, but none of these things worked. I can try to restart the whole server at night if you think it can help.

**Comment by willpower232** [comment] 2018-10-03 09:13
Interesting, this recent commit https://github.com/atech/postal/commit/cfc60d0e4182645a76fc243c888a19c431dc1b7b changed a few versions of the dependencies.

You could try resetting the Gemfile.lock and Gemfile to the previous versions and re-bundling to reset the versions installed to see if that makes a difference.

We're using the same Ruby 2.3.7 version as you but have the older Gemfiles.

**Comment by cmmata** [comment] 2018-10-04 09:02
Okay, yesterday I modified Gemfile.lock and Gemfile to have the same versions that Postal had before that commit, and now the error is gone and the certificate has finally been renewed. There's something in that vendor versions upgrade that causes the error, but I don't know how to debug and find which one.

**Comment by willpower232** [comment] 2018-10-04 12:07
Aha good to know.

I'd like to pin the blame on the lets encrypt gem which had a significant version bump but this is probably something for @catphish

**Comment by willpower232** [comment] 2018-10-17 15:09
I've just confirmed this is an issue for new installs of the latest git code so reverting back to https://github.com/atech/postal/commit/ed7889a40e1d777f1d80821043562ab18b04766e seems to be the answer for now unless @adamcooke or @catphish can provide a better answer

**Comment by afanjul** [comment] 2018-12-31 11:30
Hi there, I'm having the same error as @cmmata, previously I had to change the Gemfile **from this**:

`source 'https://rubygems.org'
gem 'rails', '= 5.2.1'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'puma', '~> 3.0'
gem 'turbolinks', '~> 5'
gem 'haml'
gem 'nifty-utils'
gem 'nilify_blanks'
gem 'kaminari'
gem 'bcrypt'
gem 'foreman'
gem 'hashie'
gem 'authie', '~> 3.0'
gem 'dynamic_form'
gem 'changey'
gem 'mail'
gem 'autoprefixer-rails'
gem 'bunny', '~> 2.5.1'
gem 'secure_headers'
gem 'chronic'
gem 'basic_ssl'
gem 'clockwork'
gem 'encrypto_signo'
gem 'nio4r'
gem 'mongo'
gem 'sentry-raven'
gem 'gelf'
gem 'moonrope'
gem 'jwt'
gem 'createsend', '~> 4.0'
gem 'acme-client'
gem 'highline', :require => true

group :development, :assets do
  gem 'sass-rails', '~> 5.0'
  gem 'uglifier', '>= 1.3.0'
  gem 'coffee-rails', '~> 4.2'
  gem 'jquery-rails'
end

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'annotate'
  gem 'rspec'
  gem 'rspec-rails'
  gem "factory_girl_rails", "~> 4.0"
  gem "database_cleaner"
end`

**to this >>>:**

`source 'https://rubygems.org'
gem 'rails', '= 5.2.1'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'puma', '~> 3.0'
gem 'turbolinks', '~> 5'
gem 'haml'
gem 'nifty-utils'
gem 'nilify_blanks'
gem 'kaminari'
gem 'bcrypt'
gem 'foreman'
gem 'hashie'
gem 'authie', '~> 3.0'
gem 'dynamic_form'
gem 'changey'
gem 'mail'
gem 'autoprefixer-rails'
gem 'bunny', '~> 2.5.1'
gem 'secure_headers'
gem 'chronic'
gem 'basic_ssl'
gem 'clockwork'
gem 'encrypto_signo'
gem 'nio4r'
gem 'mongo'
gem 'sentry-raven'
gem 'gelf'
gem 'moonrope'
gem 'jwt'
gem 'createsend', '~> 4.0'
gem 'acme-client'
gem 'highline', :require => true

gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'uglifier', '>= 1.3.0'
gem 'sass-rails', '~> 5.0'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'annotate'
  gem 'rspec'
  gem 'rspec-rails'
  gem "factory_girl_rails", "~> 4.0"
  gem "database_cleaner"
end`

So I could upgrade to the latest version using postal upgrade...(according to a solution given by an user here) Otherwise I couldn't upgrade Postal to the latest version...

but now the Lets encrypt renewing is failing....so, what is the "good" Gemfile to have?

**Comment by willpower232** [comment] 2019-01-02 13:53
> I've just confirmed this is an issue for new installs of the latest git code so reverting back to [ed7889a](https://github.com/atech/postal/commit/ed7889a40e1d777f1d80821043562ab18b04766e) seems to be the answer for now unless @adamcooke or @catphish can provide a better answer

As above, it seems the Gemfile as of that particular is usable.

**Comment by catphish** [comment] 2019-03-14 10:54
This should be fixed by c3f2adc10df9a5a8c1e0b14906f0b75c30b4e455

**Closed** 2019-03-14 11:59 UTC
