### ISSUE TITLE
Send multiple emails via API

### ISSUE THREAD

**Issue by alexroosenstein** [atech/postal#108] opened 2017-05-05 15:45 UTC
Currently when sending an email to multiple recipients, all of their emailaddresses end up in the same To field (thus, visible to all recipients).

For bulk emails it would be preferred to send separate emails to all recipients, in a single API call. On top of this, it would be great if you could send an email with variable placeholders (in the text/html) and specify data/variables per recipient, which are parsed into the email.

**Comment by alexroosenstein** [comment] 2017-05-18 08:44
I modified the API to allow sending separate emails to multiple recipients and for my case it works just fine.
I tried to maintain compatibility by adding a new parameter "recipients" to the send/message API call, and add the to, cc and bcc parameters into the recipients list.

I'm struggling a bit with the error reporting though, it currently reports back a list/array with either the message_id if it was sent successfully, or an error if it failed.

```json
{
   "status":"success",
   "time":0.09,
   "flags":{

   },
   "data":[
      {
         "to":[

         ],
         "tag":"lorem_ipsum",
         "error":"NoRecipients"
      },
      {
         "message_id":"1230412c-a8ce-4cab-b7a7-4cbed85d38b3@localhost",
         "tag":"dolor_sit_amet",
         "messages":{
            "alex@localhost":{
               "id":81,
               "token":"FjR9k7LgPxmp"
            }
         }
      }
   ]
}
```

But unfortunately this breaks compatibility, as the data variable is now a list of emails instead of a single email.
Any advice / outspoken opinions on how to proceed here?

**Comment by adamcooke** [comment] 2017-05-23 10:10
Duplicate of #183

**Closed by adamcooke** 2017-05-23 10:10 UTC
Labels: enhancement
